# Generated by Django 5.2.8 on 2025-12-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('validation_hash', models.CharField(blank=True, max_length=64)),
                ('selected_checklist_ids', models.JSONField(blank=True, default=list)),
                ('usage_types', models.JSONField(default=list)),
                ('custom_usage_type', models.TextField(blank=True)),
                ('ai_tool_name', models.CharField(max_length=200)),
                ('ai_tool_version', models.CharField(blank=True, max_length=100)),
                ('ai_tool_provider', models.CharField(blank=True, max_length=200)),
                ('ai_tool_date_month', models.IntegerField()),
                ('ai_tool_date_year', models.IntegerField()),
                ('specific_purpose', models.TextField()),
                ('prompts', models.JSONField(default=list)),
                ('content_use_modes', models.JSONField(blank=True, default=list)),
                ('custom_content_use_mode', models.TextField(blank=True)),
                ('content_use_context', models.TextField(blank=True)),
                ('human_review_level', models.IntegerField(default=0)),
                ('reviewer_name', models.CharField(blank=True, max_length=200)),
                ('reviewer_role', models.CharField(blank=True, max_length=200)),
                ('license', models.CharField(default='None', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
