# Generated by Django 5.2.8 on 2025-12-03 03:35

from django.db import migrations, models, connection


def check_and_add_is_draft(apps, schema_editor):
    """Verifica si la columna is_draft existe antes de agregarla"""
    with connection.cursor() as cursor:
        # Verificar si la columna ya existe (PostgreSQL)
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='core_declaration' AND column_name='is_draft'
        """)
        exists = cursor.fetchone()
        
        if not exists:
            # Solo agregar la columna si no existe
            cursor.execute("""
                ALTER TABLE core_declaration 
                ADD COLUMN is_draft BOOLEAN DEFAULT FALSE NOT NULL
            """)


def reverse_add_is_draft(apps, schema_editor):
    """Elimina la columna is_draft si existe"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='core_declaration' AND column_name='is_draft'
        """)
        exists = cursor.fetchone()
        
        if exists:
            cursor.execute("ALTER TABLE core_declaration DROP COLUMN is_draft")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('validation_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('hash_short', models.CharField(editable=False, max_length=8)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('orcid', models.CharField(max_length=19)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliation', models.CharField(max_length=300)),
                ('discipline', models.CharField(max_length=100)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('declaration', models.TextField(blank=True, max_length=280, null=True)),
                ('orcid_verified', models.BooleanField(default=False)),
                ('orcid_registered_name', models.CharField(blank=True, max_length=200, null=True)),
                ('agreed_to_terms', models.BooleanField(default=True)),
                ('public_listing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firmante',
                'verbose_name_plural': 'Firmantes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(
            check_and_add_is_draft,
            reverse_add_is_draft,
        ),
        # Usar SeparateDatabaseAndState para que Django sepa del campo sin intentar agregarlo
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='declaration',
                    name='is_draft',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
