# Generated by Django 5.2.8 on 2025-12-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_signer_declaration_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='signer',
            name='affiliation_ror_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
